const KEY='money-tracker-data-v1';
const DEFAULT_CATEGORIES=['Food','Transport','Shopping','Bills','Entertainment','Health','Other'];
const COLORS=['#e55d5d','#f0a34a','#8b6ce0','#4c8ee8','#e45aa8','#26a269','#7b8794'];
const seed=[
{id:'t1',type:'expense',amount:80,category:'Food',method:'UPI',description:'Dabeli from Bhai Bhai',date:'2026-10-04'},
{id:'t2',type:'expense',amount:120,category:'Transport',method:'Cash',description:'Auto',date:'2026-10-04'},
{id:'t3',type:'expense',amount:450,category:'Food',method:'UPI',description:'Dinner',date:'2026-10-03'},
{id:'t4',type:'credit',amount:30000,source:'Salary',description:'Monthly salary',date:'2026-10-01'},
{id:'t5',type:'expense',amount:1500,category:'Bills',method:'UPI',description:'Electricity',date:'2026-10-02'},
{id:'t6',type:'expense',amount:900,category:'Shopping',method:'UPI',description:'Clothes',date:'2026-10-01'}
];
function initial(){return {transactions:seed,categories:[...DEFAULT_CATEGORIES],settings:{reminder:false,reminderTime:'21:00'}}}
let state=load(); let view='home'; let historyFilter='All'; let search=''; let monthCursor=new Date(2026,9,1);
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return x||initial()}catch{return initial()}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function money(n){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n)}
function monthName(d){return d.toLocaleString('en-IN',{month:'long',year:'numeric'})}
function isoToday(){return new Date().toISOString().slice(0,10)}
function isSameMonth(date, cursor){const d=new Date(date);return d.getFullYear()===cursor.getFullYear()&&d.getMonth()===cursor.getMonth()}
function txs(){return state.transactions.filter(t=>isSameMonth(t.date,monthCursor)).sort((a,b)=>b.date.localeCompare(a.date))}
function total(type){return txs().filter(t=>t.type===type).reduce((s,t)=>s+t.amount,0)}
function esc(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function dateLabel(iso){const d=new Date(iso+'T12:00:00'), now=new Date();const today=now.toISOString().slice(0,10);const y=new Date(now);y.setDate(y.getDate()-1);const yesterday=y.toISOString().slice(0,10);if(iso===today)return 'Today';if(iso===yesterday)return 'Yesterday';return d.toLocaleDateString('en-IN',{day:'numeric',month:'short'})}
function render(){const app=document.getElementById('app');app.innerHTML=view==='home'?home():view==='expense'?form('expense'):view==='credit'?form('credit'):view==='history'?history():settings();bind();}
function home(){const expenses=total('expense'), credits=total('credit'), remain=credits-expenses;const cat=state.categories.map((c,i)=>({name:c,amount:txs().filter(t=>t.type==='expense'&&t.category===c).reduce((s,t)=>s+t.amount,0),color:COLORS[i%COLORS.length]})).filter(x=>x.amount).sort((a,b)=>b.amount-a.amount);const recent=txs().slice(0,4);return `<div class="screen"><div style="display:flex;justify-content:space-between;align-items:flex-start"><div><h1 class="title">${monthName(monthCursor)}</h1><p class="subtitle">Personal money overview</p></div><button class="chip" data-act="settings" aria-label="Settings">⚙</button></div><div class="card month-nav"><button data-act="prev-month">‹</button><span>${monthName(monthCursor)}</span><button data-act="next-month">›</button></div><div class="summary"><div><div class="stat-label">Credit</div><div class="stat-value green">${money(credits)}</div></div><div><div class="stat-label">Spending</div><div class="stat-value red">${money(expenses)}</div></div><div><div class="stat-label">Remaining</div><div class="stat-value">${money(remain)}</div></div></div><h2 class="section-title">Spending by category</h2><div class="card category-card">${cat.length?cat.map(x=>{const p=Math.round(x.amount/(expenses||1)*100);return `<div class="category-row"><span class="dot" style="background:${x.color}"></span><span>${esc(x.name)}</span><span class="category-meta">${money(x.amount)} &nbsp; ${p}%</span></div>`}).join(''):'<div class="empty">No expenses for this month.</div>'}</div><h2 class="section-title">Recent transactions</h2><div class="tx-list">${recent.length?recent.map(txRow).join(''):'<div class="card empty">No transactions yet.</div>'}</div><button class="fab" data-act="expense">＋ &nbsp; Add Expense</button>${nav('home')}</div>`}
function txRow(t){return `<div class="card tx" data-tx="${t.id}"><div class="tx-amount ${t.type==='credit'?'green':'red'}">${t.type==='credit'?'+':''}${money(t.amount)}</div><div class="tx-main"><div class="tx-desc">${esc(t.description||t.source||t.category)}</div><div class="tx-meta">${esc(t.type==='credit'?t.source:t.category)}${t.method?' · '+esc(t.method):''}</div></div><div class="tx-date">${dateLabel(t.date)}</div></div>`}
function form(type){const credit=type==='credit';return `<div class="screen form-screen"><button class="back" data-act="back">‹ &nbsp; Back</button><h1 class="form-title">${credit?'Add Credit':'Add Expense'}</h1><p class="form-subtitle">${credit?'Record money coming in.':'Record money you spent.'}</p><form id="tx-form"><div class="field"><label>Amount</label><input class="input amount-input" name="amount" type="number" inputmode="decimal" min="1" step="1" placeholder="₹ 0" required autofocus></div>${credit?`<div class="field"><label>Source</label><div class="chips">${['Salary','Freelance','Pocket Money','Other'].map(x=>`<button type="button" class="chip source-chip" data-value="${x}">${x}</button>`).join('')}</div><input class="input" name="source" placeholder="Or enter a source" style="margin-top:9px"></div>`:`<div class="field"><label>Category</label><div class="chips">${state.categories.map(x=>`<button type="button" class="chip cat-chip" data-value="${esc(x)}">${esc(x)}</button>`).join('')}</div></div><div class="field"><label>Payment method</label><div class="segmented"><button type="button" class="seg method selected" data-value="UPI">UPI</button><button type="button" class="seg method" data-value="Cash">Cash</button></div></div>`}<div class="field"><label>${credit?'Optional note':'Description (optional)'}</label><input class="input" name="description" placeholder="${credit?'e.g. October salary':'e.g. What was it for?'}"></div><div class="field"><label>Date</label><input class="input" name="date" type="date" value="${isoToday()}" required></div><button class="primary" type="submit">${credit?'Add Credit':'Add Expense'}</button>${!credit?'<button type="button" class="secondary" data-act="custom-category">＋ Create custom category</button>':''}</form></div>`}
function history(){let list=state.transactions.filter(t=>{const q=search.toLowerCase();const text=[t.description,t.category,t.source,t.method].filter(Boolean).join(' ').toLowerCase();const f=historyFilter==='All'||(historyFilter==='Credit'&&t.type==='credit')||(historyFilter==='Debit'&&t.type==='expense')||(historyFilter==='Food'&&t.category==='Food')||(historyFilter==='UPI'&&t.method==='UPI');return (!q||text.includes(q))&&f}).sort((a,b)=>b.date.localeCompare(a.date));return `<div class="screen"><button class="back" data-act="back">‹ &nbsp; Back</button><h1 class="form-title">Transaction History</h1><p class="form-subtitle">Everything in one place.</p><div class="toolbar"><input class="search" id="history-search" placeholder="Search transactions" value="${esc(search)}"><button class="chip" data-act="clear-search">Clear</button></div><div class="filter-scroll">${['All','Credit','Debit','Food','UPI'].map(f=>`<button class="chip ${historyFilter===f?'selected':''}" data-filter="${f}">${f}</button>`).join('')}</div><div style="margin-top:14px" class="tx-list">${list.length?list.map(txRow).join(''):'<div class="card empty">No matching transactions.</div>'}</div>${nav('history')}</div>`}
function settings(){return `<div class="screen"><button class="back" data-act="back">‹ &nbsp; Back</button><h1 class="form-title">Settings</h1><p class="form-subtitle">Keep the tracker simple and private.</p><div class="card settings-card"><div class="setting-row"><div><div class="setting-title">Dark mode</div><div class="setting-desc">Use a darker theme that's easier on the eyes.</div></div><button class="toggle ${state.settings.darkMode?'on':''}" data-act="toggle-dark" aria-label="Toggle dark mode"></button></div><div class="setting-row"><div><div class="setting-title">Daily expense reminder</div><div class="setting-desc">Optional reminder for logging your daily expenses.</div></div><button class="toggle ${state.settings.reminder?'on':''}" data-act="toggle-reminder" aria-label="Toggle reminder"></button></div><div class="setting-row"><div><div class="setting-title">Phone alarm time</div><div class="setting-desc">${state.settings.alarmTime||'21:00'}</div></div><input type="time" value="${state.settings.alarmTime||'21:00'}" data-act="alarm-time" style="border:0;background:transparent"></div><div class="setting-row"><div><div class="setting-title">Alarm label</div><div class="setting-desc">${esc(state.settings.alarmLabel||"Log today's expenses")}</div></div><button class="chip" data-act="alarm-label">Edit</button></div><div class="setting-row"><div><div class="setting-title">Set phone alarm</div><div class="setting-desc">Opens Android's Clock alarm screen. The PWA does not need to stay running.</div></div><button class="chip" data-act="set-alarm">Set</button></div><div class="setting-row"><div><div class="setting-title">Storage</div><div class="setting-desc">All data stays in this browser on this device.</div></div><span style="font-size:12px;color:var(--green)">Local</span></div><div class="setting-row"><div><div class="setting-title">Sample data</div><div class="setting-desc">Reset the app back to the demo transactions.</div></div><button class="chip" data-act="reset">Reset</button></div><div class="setting-row"><div><div class="setting-title danger">Clear all data</div><div class="setting-desc">Permanently clear transactions and custom categories.</div></div><button class="chip" data-act="clear">Clear</button></div></div><p class="small-note">This version intentionally has no account, server, analytics, or cloud sync.</p>${nav('settings')}</div>`}
function nav(active){return `<nav class="bottom-nav"><button class="nav-btn ${active==='home'?'active':''}" data-act="home"><span class="nav-icon">⌂</span>Home</button><button class="nav-btn ${active==='credit'?'active':''}" data-act="credit"><span class="nav-icon">＋</span>Credit</button><button class="nav-btn ${active==='expense'?'active':''}" data-act="expense"><span class="nav-icon">−</span>Debit</button><button class="nav-btn ${active==='history'?'active':''}" data-act="history"><span class="nav-icon">☷</span>History</button></nav>`}
function bind(){document.querySelectorAll('[data-act]').forEach(el=>el.addEventListener('click',()=>act(el.dataset.act)));document.querySelectorAll('[data-filter]').forEach(el=>el.addEventListener('click',()=>{historyFilter=el.dataset.filter;render()}));document.querySelectorAll('.cat-chip').forEach(el=>el.addEventListener('click',()=>{document.querySelectorAll('.cat-chip').forEach(x=>x.classList.remove('selected'));el.classList.add('selected')}));document.querySelectorAll('.source-chip').forEach(el=>el.addEventListener('click',()=>{document.querySelectorAll('.source-chip').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');document.querySelector('[name=source]').value=el.dataset.value}));document.querySelectorAll('.method').forEach(el=>el.addEventListener('click',()=>{document.querySelectorAll('.method').forEach(x=>x.classList.remove('selected'));el.classList.add('selected')}));const formEl=document.getElementById('tx-form');if(formEl)formEl.addEventListener('submit',submitTx);const searchEl=document.getElementById('history-search');if(searchEl)searchEl.addEventListener('input',e=>{search=e.target.value;render();setTimeout(()=>{const s=document.getElementById('history-search');if(s){s.focus();s.setSelectionRange(search.length,search.length)}},0)});document.querySelectorAll('[data-tx]').forEach(el=>el.addEventListener('click',()=>editTx(el.dataset.tx)));const at=document.querySelector('[data-act="alarm-time"]');if(at)at.addEventListener('change',e=>{state.settings.alarmTime=e.target.value;save();toast('Alarm time saved')})}
function act(a){if(a==='home'){go('home')}else if(a==='expense'||a==='credit'){go(a)}else if(a==='history'){go('history')}else if(a==='settings'){go('settings')}else if(a==='back'){goBack()}else if(a==='prev-month'){monthCursor.setMonth(monthCursor.getMonth()-1);render()}else if(a==='next-month'){monthCursor.setMonth(monthCursor.getMonth()+1);render()}else if(a==='custom-category'){const x=prompt('Category name');if(x&&x.trim()){const c=x.trim();if(!state.categories.includes(c))state.categories.push(c);save();render()}}else if(a==='toggle-dark'){state.settings.darkMode=!state.settings.darkMode;save();applyTheme();render()}else if(a==='alarm-label'){const x=prompt('Alarm label',state.settings.alarmLabel||"Log today's expenses");if(x&&x.trim()){state.settings.alarmLabel=x.trim();save();render()}}else if(a==='set-alarm'){setPhoneAlarm()}else if(a==='reset'){if(confirm('Reset to sample data?')){state=initial();save();applyTheme();render();toast('Sample data restored')}}else if(a==='clear'){if(confirm('Clear all transactions and categories?')){state={transactions:[],categories:[...DEFAULT_CATEGORIES],settings:state.settings};save();render();toast('All data cleared')}}else if(a==='clear-search'){search='';render()}}
function setPhoneAlarm(){const [h,m]=(state.settings.alarmTime||'21:00').split(':').map(Number);const label=state.settings.alarmLabel||"Log today's expenses";const intent='intent:#Intent;action=android.intent.action.SET_ALARM;i.android.intent.extra.alarm.HOUR='+h+';i.android.intent.extra.alarm.MINUTES='+m+';S.android.intent.extra.alarm.MESSAGE='+encodeURIComponent(label)+';end';location.href=intent}
function applyTheme(){document.documentElement.dataset.theme=state.settings.darkMode?'dark':'light';const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content=state.settings.darkMode?'#0f1319':'#f6f8fa'}
function submitTx(e){e.preventDefault();const fd=new FormData(e.currentTarget);const amount=Number(fd.get('amount'));if(!amount||amount<=0){toast('Enter a valid amount');return}const type=view;const category=document.querySelector('.cat-chip.selected')?.dataset.value;const source=fd.get('source')?.toString().trim()||document.querySelector('.source-chip.selected')?.dataset.value||'Other';if(type==='expense'&&!category){toast('Choose a category');return}const tx={id:'t'+Date.now(),type,amount,date:fd.get('date'),description:fd.get('description')?.toString().trim()||'',...(type==='expense'?{category,method:document.querySelector('.method.selected')?.dataset.value||'UPI'}:{source})};state.transactions.push(tx);save();view='home';monthCursor=new Date(tx.date+'T12:00:00');render();toast(type==='expense'?'Expense added':'Credit added')}
function editTx(id){const t=state.transactions.find(x=>x.id===id);if(!t)return;const action=prompt(`${t.type==='credit'?'Credit':'Expense'}: ${money(t.amount)}\n${t.description||t.category||t.source}\n\nType DELETE to remove this transaction, or Cancel to keep it.`);if(action==='DELETE'){state.transactions=state.transactions.filter(x=>x.id!==id);save();render();toast('Transaction deleted')}}
function toast(msg){const old=document.querySelector('.toast');if(old)old.remove();const el=document.createElement('div');el.className='toast';el.textContent=msg;document.body.appendChild(el);setTimeout(()=>el.remove(),1800)}
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
applyTheme();
render();
